### PR TITLE
Sweep attributes on GenericParameters and InterfaceImplementations

### PR DESCRIPTION
**Pull request by sbomer**
This fixes test failures that show up due to NullableAttribute with recent versions of .NET Core (see the failures in https://github.com/mono/linker/pull/570). This should unblock the dependency uptake.

### CODE REVIEW

**Comment by sbomer** [comment]
@marek-safar @mrvoorhe PTAL

**Comment by mrvoorhe** [comment]
Can you add a test so that we have coverage on this?  You may need to make it an IL test.  There are a few other IL tests that you could use as an example.

**Comment by sbomer** [comment]
I tried adding a test with an attribute on `.interfaceimpl`, but had trouble getting it to assemble. I'll give it another shot today.

**Comment by sbomer** [comment]
Looks like the coreclr-built ilasm supports `.interfaceimpl` (https://github.com/dotnet/coreclr/blob/fe2adecea97d58997a0164df3dd6cdb8fa473f9d/src/ilasm/asmparse.y#L74), but I'm not finding this token in mono's version: https://github.com/mono/mono/blob/6a81662247af5dd09881ec986eb6b9729dc7fa59/mcs/ilasm/parser/ILParser.jay. I'll see if I can at least get it working for generic parameters.

**Comment by sbomer** [comment]
I added a test for the GenericParameter attribute sweeping. Without the fix, this test fails like so:
```
Failed   OnlyKeepUsed.UnusedAttributeOnGenericParameterIsRemoved
Error Message:
 System.ArgumentException : Member 'System.Void Mono.Linker.Tests.Cases.Attributes.OnlyKeepUsed.Dependencies.FooAttribute::.ctor()' is declared in another module and needs to be imported
Stack Trace:
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider) in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 2243
   at Mono.Cecil.MetadataBuilder.AddCustomAttributes(ICustomAttributeProvider owner) in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1959
   at Mono.Cecil.MetadataBuilder.AddGenericParameters() in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1507
   at Mono.Cecil.MetadataBuilder.BuildTypes() in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1260
   at Mono.Cecil.MetadataBuilder.BuildModule() in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 1029
   at Mono.Cecil.MetadataBuilder.BuildMetadata() in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 999
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _) in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 137
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read) in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/ModuleDefinition.cs:line 953
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata) in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 136
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 115
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/AssemblyWriter.cs:line 77
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters) in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/ModuleDefinition.cs:line 1142
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters) in /Users/sven/src/dotnet/linker/external/cecil/Mono.Cecil/AssemblyDefinition.cs:line 160
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters) in /Users/sven/src/dotnet/linker/src/linker/Linker.Steps/OutputStep.cs:line 106
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory) in /Users/sven/src/dotnet/linker/src/linker/Linker.Steps/OutputStep.cs:line 92
   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly) in /Users/sven/src/dotnet/linker/src/linker/Linker.Steps/OutputStep.cs:line 123
   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly) in /Users/sven/src/dotnet/linker/src/linker/Linker.Steps/OutputStep.cs:line 87
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context) in /Users/sven/src/dotnet/linker/src/linker/Linker.Steps/BaseStep.cs:line 61
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step) in /Users/sven/src/dotnet/linker/src/linker/Linker/Pipeline.cs:line 134
   at Mono.Linker.Pipeline.Process(LinkContext context) in /Users/sven/src/dotnet/linker/src/linker/Linker/Pipeline.cs:line 126
   at Mono.Linker.Driver.Run(ILogger customLogger) in /Users/sven/src/dotnet/linker/src/linker/Linker/Driver.cs:line 386
   at Mono.Linker.Tests.TestCasesRunner.LinkerDriver.Link(String[] args) in /Users/sven/src/dotnet/linker/test/Mono.Linker.Tests/TestCasesRunner/LinkerDriver.cs:line 5
   at Mono.Linker.Tests.TestCasesRunner.TestRunner.Link(TestCase testCase, TestCaseSandbox sandbox, ManagedCompilationResult compilationResult, TestCaseMetadaProvider metadataProvider) in /Users/sven/src/dotnet/linker/test/Mono.Linker.Tests/TestCasesRunner/TestRunner.cs:line 93
   at Mono.Linker.Tests.TestCasesRunner.TestRunner.Run(TestCase testCase) in /Users/sven/src/dotnet/linker/test/Mono.Linker.Tests/TestCasesRunner/TestRunner.cs:line 30
   at Mono.Linker.Tests.TestCases.All.Run(TestCase testCase) in /Users/sven/src/dotnet/linker/test/Mono.Linker.Tests/TestCases/TestSuites.cs:line 169
   at Mono.Linker.Tests.TestCases.All.AttributesTests(TestCase testCase) in /Users/sven/src/dotnet/linker/test/Mono.Linker.Tests/TestCases/TestSuites.cs:line 31
```

**Pull request merged**
