### PR TITLE
Sweep EntryPoint method reference

### LINKED ISSUE #1713: Linker OutputStep failing
When running `dotnet/runtime` library tests in the effort to trim out assemblies, this linker error is hit. 
```
ILLink: error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues
Fatal error in IL Linker
Unhandled exception. Mono.Linker.InternalErrorException: Step 'OutputStep' failed when processing assembly 'Microsoft.DotNet.RemoteExecutor, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
 ---> Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'linked/Microsoft.DotNet.RemoteExecutor.dll
 ---> System.ArgumentException: Member 'System.Int32 Microsoft.DotNet.RemoteExecutor.Program::Main(System.String[])' is declared in another module and needs to be imported
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Main(String[] args)
Abort trap: 6
```

Zip file repro steps
Unzip the following and modify the first part of `repro.sh` `/Users/mdhwang/runtime_wasm_clean/.dotnet/dotnet "/Users/mdhwang/.nuget/packages/microsoft.net.illink.tasks/6.0.0-alpha.1.20621.1/tools/net5.0/illink.dll"` to conform to local dotnet and illink.
[OutputStepLinker.zip](https://github.com/mono/linker/files/5731959/OutputStepLinker.zip)

Dotnet/runtime repro steps
Check out https://github.com/mdh1418/runtime/commits/mdhwang/trim_library_tests_linker_bug
In the repo root
`./build.sh -os Browser -arch wasm -c Debug`
`./dotnet.sh build /t:Test src/libraries/System.Buffers/tests/ /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Debug /p:RunNormal=true`

/cc @marek-safar

### PR DESCRIPTION
**Pull request by marek-safar**
Fixes #1713

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
If this is the behavior we want to codify, we need to mark https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.entrypoint?view=net-5.0 as RequiresUnreferencedCode. The API is currently considered trimming safe.

**Comment by vitek-karas** [comment]
I'm not sure I like this - mainly due to the issue which Michal raised. `Assembly.EntryPoint` will be trim-compatible in almost all cases, except for these special projects which refer to .exe as a library. I would probably prefer to make linker always preserve entry-point on an assembly, regardless if it's a main app assembly or not. So that we don't have to make the EntryPoint API trim-incompatible.

Otherwise we would basically ask everybody who uses that API to suppress the warning - that's a bad experience.

**Comment by marek-safar** [comment]
I think these are two separate things.

The PR fixes a crash because linker keeps dangling method reference to a removed method it does not change linker behaviour regarding of Assembly.EntryPoint.

Michal raised a point about Assembly.EntryPoint which today linker does not keep either and this PR does not change. We could always preserve all entry-points everywhere but we have a case in dotnet/runtime which adds I think over 10% because of that so we'd need to add a way to opt-out from that. Another option would be to teach linker to recognize Assembly.EntryPoint reference and make the logic conditional.

**Comment by vitek-karas** [comment]
Thanks @marek-safar for clarification. Just curious what (roughly) is the case in dotnet/runtime which causes such a large size impact?

**Comment by marek-safar** [comment]
Large is relative here, the team is working on getting each libraries tests under 2MB and we hit some unnecessary dependency in xunit runner.

Thinking about the options we could also just document that if someone needs to keep entry point in "non-default" assembly they need to add it to the AssemblyRootEntryPoint items

**Comment by vitek-karas** [comment]
That would still not solve the annotation/warning problem - the API would still have to be annotated as dangerous. Unless we go with the intrinsic approach - what could work.

**Comment by marek-safar** [comment]
Made #1729 issue about Assembly.EntryPoint API handling

**Review by vitek-karas — APPROVED** [review]

**Pull request merged**
