### PR TITLE
Fix submodule option on build jobs

### PR DESCRIPTION
**Pull request by sbomer**
The argument to setRecursiveSubmoduleOption should be newJob.

### CODE REVIEW

**Comment by sbomer** [comment]
test ci please

**Comment by sbomer** [comment]
test ci please

**Comment by sbomer** [comment]
test ci please

**Comment by sbomer** [comment]
test ci please

**Comment by sbomer** [comment]
@mmitche PTAL.
Originally I added the recursive submodule option without realizing that this would remove the existing git options set by standardJobSetup. Using a configure block seems to fix this, but I'm not sure if there's a cleaner way to do this.

**Comment by sbomer** [comment]
See https://ci2.dot.net/job/mono_linker/job/master/job/GenPRTest/job/windows_nt_prtest/4/ for the job that ran with the fixed submodule option - the build was successful.

**Comment by mmitche** [comment]
LGTM.  Yeah you'd need to create a full scm block to do it without recursive submodules.  Otherwise it overwrites the old scm block.

**Pull request merged**
