### PR TITLE
Fix mdb symbol handling.

### PR DESCRIPTION
**Pull request by mrvoorhe**
All that was needed was to reference Mono.Cecil.Mdb so that the assembly would be built

### CODE REVIEW

**Comment by mrvoorhe** [comment]
@marek-safar Do you know what project system incantation I'm missing to make the build happy?

**Comment by marek-safar** [comment]
Try to update https://github.com/mono/linker/blob/master/monobuild/Makefile#L14

**Comment by mrvoorhe** [comment]
Thanks.  Fixed

**Comment by mrvoorhe** [comment]
Didn't realize corebuild had a copy of linker.sln that needed updated.  Hopefully the build is fixed now 🤞

**Comment by mrvoorhe** [comment]
build

**Comment by mrvoorhe** [comment]
@marek-safar @sbomer Any idea what I'm missing to make the corebuild happy?

**Comment by sbomer** [comment]
@mrvoorhe looks to me like the corebuild jobs (Ubuntu Build and Windows_NT Build) are passing now. I'm not familiar with the Linux - Mono build, and the build log isn't terribly helpful. It mentions something about broken packages in a chroot:
```
18:09:47 $ sudo /usr/sbin/pbuilder --update --basetgz /mnt/jenkins/workspace/test-linker-pull-request/ubuntu-1404-amd64-stable/ubuntu-1404-amd64-stable.tgz --extrapackages "mono-devel mono-utils msbuild nuget git"
18:09:47 W: /home/builder/.pbuilderrc does not exist
18:09:51 W: No local /etc/mailname to copy, relying on /mnt/jenkins/buildplace/76997/etc/mailname to be correct
18:10:03 E: Unable to correct problems, you have held broken packages.
```

**Comment by marek-safar** [comment]
build

**Pull request merged**
