### PR TITLE
Simplify solutions used to build monolinker/illink

### PR DESCRIPTION
**Pull request by sbomer**
Until I can make more progress on SDK-style projects (see https://github.com/mono/linker/pull/471), I'll begin trying to set up a build of illink using arcade and the old-style projects. In this change I'm getting rid of the scattered linker.sln files in favor of monolinker.sln for monolinker, and illink.sln for the illink/ILLink.Tasks build.

### CODE REVIEW

**Comment by sbomer** [comment]
build

**Comment by sbomer** [comment]
@marek-safar the Linux - Mono build definition is failing because of the solution rename. What does it take to update the build definition?

**Comment by marek-safar** [comment]
@akoeplinger I think we need to update it on Jenkins, right?

**Comment by akoeplinger** [comment]
should be fixed.

@monojenkins build

**Pull request merged**
