### PR TITLE
Use ServerGarbageCollection=true

### PR DESCRIPTION
**Pull request by mateoatr**
Following @MichalStrehovsky advice I set the `ServerGarbageCollection`... and it looks good.

The server GC mode allows for multiple GC threads to exists simultaneously - one for each CPU available. It improves the throughput of the linker quite a bit by allowing the GC to process as much data as it can in a time unit. Trade off here is memory cost: memory use will be higher, since GCs will happen less often.

Linking a hello world app with `ServerGarbageCollection` set improves the linker total CPU time by ~20% (20,600ms vs 16,380ms) and brings down the total GC pause from 4,816.2ms to 317.4ms, the peak GC process working set augmented from 304MB to 371MB (of course perf gains are dependent upon # of CPUs - I ran this on a machine with 6 processors.)

### CODE REVIEW

**Review by MichalStrehovsky — APPROVED** [review]
Nice!

**Comment by marek-safar** [comment]
I guess this setting will be used only for the very uncommon case where you call illink directly.

**Comment by MichalStrehovsky** [comment]
> I guess this setting will be used only for the very uncommon case where you call illink directly.

I thought the ILLink task launches linker in a separate dotnet process - isn't that the case? This setting should be propagated to the runtimeconfig.json file.

**Review by vitek-karas — APPROVED** [review]

**Comment by marek-safar** [comment]
@MichalStrehovsky makes sense

**Pull request merged**
