### PR TITLE
Add ILLink.Shared shared project

### PR DESCRIPTION
**Pull request by mateoatr**
We already share code between analyzer and linker, this only adds a shared project that makes intentions more transparent and files easily discoverable inside VS. Moving forward with the analyzer, I think we'd like to share more and more code between the two; for one, I'd like to share as much as possible related to the diagnostic creation / warnings.

### CODE REVIEW

**Comment by tlakollo** [comment]
So initially the ILLink.Shared was a project, but was decided to not keep it as one see: https://github.com/mono/linker/pull/2098#discussion_r653308654
So far I think the additional resources work, is there anything different you want to make that would be easier if we had a project?

**Comment by mateoatr** [comment]
> So initially the ILLink.Shared was a project, but was decided to not keep it as one see: [#2098 (comment)](https://github.com/mono/linker/pull/2098#discussion_r653308654)
> So far I think the additional resources work, is there anything different you want to make that would be easier if we had a project?

If we have a supported way of sharing files within projects, I don't see any reason not to use it. I plan on adding a bunch more of diagnostics to the SharedStrings.resx file as part of the DAM analyzer (and hopefully, more code related to how we log/process diagnostics).

Also, it's nice having the file structure as clear as:
image

vs:
image

**Comment by tlakollo** [comment]
I'm actually fine with having an additional project, and indeed looks easier to work with the files

**Review by tlakollo — APPROVED** [review]
There is some shared project logic I'm not very familiar with, but the changes look good

**Pull request merged**
