### PR TITLE
Add a test for attribute removal using wildcard and lazy loading

### PR DESCRIPTION
**Pull request by vitek-karas**
Currently this doesn't work as it should, the test is to cover the scenario - once we fully implement lazy loading this should be fixed.

### CODE REVIEW

**Review by marek-safar — APPROVED** [review]

**Comment by sbomer** [comment]
Didn't we decide that the wildcard was only supported for corelib? https://github.com/mono/linker/pull/1675 intentionally removed support for `*` in embedded XML except corelib. I would expect that the attribute isn't removed in this case, with or without lazy loading.

**Comment by vitek-karas** [comment]
Good point - that basically means there's no way to write a test for it, right? (I can't fake corelib)
But the functionality is still broken...
Should we maybe add some test hook to enable it on other assemblies so that it can be tested?

Also - this pretty much means that the LinkerAttributeRemoval test should not work, right? So how come it's passing?

**Comment by sbomer** [comment]
It's a bit of a hack, but I managed to write a test that mocks corelib: https://github.com/mono/linker/pull/1675/files#diff-6bc3fb243979b37206fe4be289fcc1c77b1b6ec8173e7e63a090603639dd7c75R20. It fails PeVerify because system types can't be resolved, but it does check the attribute removal in other assemblies.

As to why the test is passing - I just noticed it's actually not using embedded xml. :) SetupLinkAttributesFile will use the command-line xml.

**Comment by vitek-karas** [comment]
Good point about the file not being embedded - in that case the test is perfectly valid, right?

**Comment by sbomer** [comment]
Right, good point. And it's a good test to have, since I have been focusing mostly on the embedded XML.

**Review by sbomer — APPROVED** [review]

**Pull request merged**
