### PR TITLE
Update to recent nunit test adapter and clean up unused dependencies

### PR DESCRIPTION
**Pull request by marek-safar**
Depends on #1475

### CODE REVIEW

**Review by vitek-karas — APPROVED** [review]
Looks good - we should validate that it works with VS - that is, it's still possible to run tests from within VS itself.

**Comment by marek-safar** [comment]
I don't have VS setup available

**Comment by vitek-karas** [comment]
OK - I'll try it

**Comment by vitek-karas** [comment]
Verified that it works with VS.

**Pull request merged**
